sudo: required
addons:
  chrome: stable

language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    ## Cache NPM folder and Cypress binary
    ## to avoid downloading Cypress again and again
    - ~/.npm
    - ~/.cache

install:
  - npm install -g yarn
  - npm install -g @angular/cli
  # https://docs.cypress.io/guides/guides/continuous-integration.html#We-recommend-users
  # Caching ~/.cache will include both the yarn and Cypress caches. Consider
  # using yarn install --frozen-lockfile as an npm ci equivalent.
  - yarn install --frozen-lockfile

script:
  - yarn test
  - yarn run cypress:ci
