sudo: required
addons:
  chrome: stable

language: node_js

# https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines
env:
  - PARALLEL_NUM=1
  - PARALLEL_NUM=2
  - PARALLEL_NUM=3
  - PARALLEL_NUM=4

node_js:
  - 10

cache:
  yarn: true
  directories:
    ## Cache NPM folder and Cypress binary
    ## to avoid downloading Cypress again and again
    - ~/.npm
    - ~/.cache

install:
  - npm install -g yarn
  - npm install -g @angular/cli
  # https://docs.cypress.io/guides/guides/continuous-integration.html#We-recommend-users
  # Caching ~/.cache will include both the yarn and Cypress caches. Consider
  # using yarn install --frozen-lockfile as an npm ci equivalent.
  - yarn install --frozen-lockfile

before_script:
  # serve app in background
  - ng serve --configuration=ci &

script:
  # record tests and upload them to cypress dashboard
  # parallel to spread across VMs initialized by travis for `env` matrix
  # port defined in angular.json (projects:cypress-github-demo:architect:serve:configurations:ci:port)
  - $(npm bin)/cypress run --record --parallel --config baseUrl="http://localhost:8888"
