sudo: required
addons:
  chrome: stable

language: node_js

# https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines
env:
  - PARALLEL_NUM=1
  - PARALLEL_NUM=2
  - PARALLEL_NUM=3
  - PARALLEL_NUM=4

node_js:
  - 10

cache:
  yarn: true
  directories:
    ## Cache NPM folder and Cypress binary
    ## to avoid downloading Cypress again and again
    - ~/.npm
    - ~/.cache

install:
  - npm install -g yarn
  - npm install -g @angular/cli
  # https://docs.cypress.io/guides/guides/continuous-integration.html#We-recommend-users
  # Caching ~/.cache will include both the yarn and Cypress caches. Consider
  # using yarn install --frozen-lockfile as an npm ci equivalent.
  - yarn install --frozen-lockfile

before_script:
  # serve app in background
  - yarn run start -- --port 8888 &

script:
  # use Chrome instead of built in Electron browser
  - yarn run cypress:run --  --record --parallel --browser chrome
