sudo: required
addons:
  chrome: stable

language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    ## Cache NPM folder and Cypress binary
    ## to avoid downloading Cypress again and again
    - ~/.npm
    - ~/.cache

install:
  - npm install -g yarn
  - npm install -g @angular/cli
  # https://docs.cypress.io/guides/guides/continuous-integration.html#We-recommend-users
  # Caching ~/.cache will include both the yarn and Cypress caches. Consider
  # using yarn install --frozen-lockfile as an npm ci equivalent.
  - yarn install --frozen-lockfile

before_script:
  ## runs the 'start' script which
  ## boots our local app server on port 8888
  ## which cypress expects to be running
  ## -----------------------------------
  ## the '-- --silent' passes arguments
  ## to http-server which silences its output
  ## else our travis logs would be cluttered
  ## with output from HTTP requests
  ## https://docs.npmjs.com/cli/start
  ## https://github.com/indexzero/http-server
  ## ---------------------------------------
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  # - npm start -- --silent &
  - ng serve &

script:
  - yarn test
  - $(npm bin)/cypress run --record
