sudo: required
addons:
  chrome: stable

language: node_js

# https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines
env:
  - PARALLEL_NUM=1
  - PARALLEL_NUM=2
  - PARALLEL_NUM=3

node_js:
  - 10

cache:
  yarn: true
  directories:
    ## Cache NPM folder and Cypress binary
    ## to avoid downloading Cypress again and again
    - ~/.npm
    - ~/.cache

install:
  - npm install -g yarn
  - npm install -g @angular/cli
  # https://docs.cypress.io/guides/guides/continuous-integration.html#We-recommend-users
  # Caching ~/.cache will include both the yarn and Cypress caches. Consider
  # using yarn install --frozen-lockfile as an npm ci equivalent.
  - yarn install --frozen-lockfile

before_script:
  # serve app in background
  - ng serve --port=8888 --progress=false &
  # wait for webserver to respond before
  - until curl -vs -o /dev/null http://localhost:8888 2>&1; do true; done > /dev/null

script:
  # record tests and upload them to cypress dashboard
  # parallel to spread across VMs initialized by travis for `env` matrix
  - cypress run --record --parallel --config baseUrl="http://localhost:8888"
